# Add configuration values here, as shown below.
#   DATABASE   -   -   -   -   -   -   -   -
db_adapter: sqlite3
db_timeout: 5000
db_pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
db_name_dev: db/development.sqlite3
db_name_prod: db/development.sqlite3
db_name_test: db/development.sqlite3
